- name: Test SSH Connectivity
  hosts: all
  gather_facts: no
  vars_files:
    - ../vars/vars_sensitive.yaml
  remote_user: "{{ rocky_linux_user }}"
  tasks:
    - name: Ping the hosts
      ping:

    - name: Debug the private key file
      debug:
        var: ansible_ssh_private_key_file